version: 2
jobs:
  test:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-npm-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}
          paths:
          - node_modules
      - run: ./scripts/ios-test.sh
      - store_test_results:
          path: /tmp/xcode
      - store_artifacts:
          path: /tmp/xcode_raw.log
          destination: xcode-raw-logs

workflows:
  version: 2
  test:
    jobs:
      - test
